changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
    authors:
      - dependabot
      - dependabot[bot]
      - github-actions
      - github-actions[bot]

  categories:
    - title: "Breaking Changes"
      labels:
        - breaking

    - title: "Bug Fixes"
      labels:
        - bug
        - fix

    - title: "Other Changes"
      labels:
        - "*"
