name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ihs7/action-sha-pinned-actions@e805c42c9e2c7deb3f339079c143507c28df129f # v1.0.0

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org

      - run: bun install --frozen-lockfile

      - run: bun run format:check

      - run: bun run lint

      - run: bun test

      - run: bun run build

      - name: Version check
        id: version-check
        uses: EndBug/version-check@095362f3cd50f690c8fa0e6afeea81834bd8d320 # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          static-checking: localIsNew
          file-url: https://unpkg.com/@ihs7/umbra/package.json

      - name: Publish
        if: steps.version-check.outputs.changed == 'true'
        run: npm publish --access public

      - name: Tag release
        if: steps.version-check.outputs.changed == 'true'
        run: |
          git tag "v${{ steps.version-check.outputs.version }}"
          git push origin "v${{ steps.version-check.outputs.version }}"
